# YOLO dataset configuration for port operations
# Update the absolute/relative paths as needed
path: F:/python/configuration/dataset_yolo
train: images/train
val: images/val
test: images/test

names:
  0: ship
  1: container
  2: crane

