# YOLO dataset configuration for public port dataset
path: f:/python/configuration_harbor/dataset_yolo_public
train: images/train
val: images/val
test: images/test

names:
  0: ship
  1: container
  2: crane